name: prod Playwright Tests
on:
  schedule:
    - cron:  '30 23,7 * * *' # UTC 23:30と7:30に(JST 8:30と16:30)動く
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Install Playwright
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"
      - name: Run tests on chromium
        run: mvn -Dplaywright.browser-type=chromium test
      - name: Run tests on firefox
        run: mvn -Dplaywright.browser-type=firefox test
      - name: Run tests on webkit
        run: mvn -Dplaywright.browser-type=webkit test
